### ISSUE TITLE
attempt to call method 'gsub' (a nil value)

### ISSUE THREAD

**Issue by do0dleme** [fluxionary/minetest-fmod#1]
`: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback item_OnUse(): ...w/multicraft/bin/../builtin/common/misc_helpers.lua:613: attempt to call method 'gsub' (a nil value)`
`2022-12-02 14:58:58: ERROR[Main]: stack traceback:`                                                                                                                                                   
`2022-12-02 14:58:58: ERROR[Main]:      ...s/multicraft/bin/../builtin/common/misc_helpers.lua:613: in function 'S'`                                                                                   `2022-12-02 14:58:58: ERROR[Main]:      ..s/worlds/world/worldmods/minetest-fmod/init.lua:79: in function 'chat_send_all'`                                                                              `2022-12-02 14:58:58: ERROR[Main]:      ...rldmods/minetest-replacer_redo/replacer/api/replacer.lua:157: in function <...rldmods/minetest-replacer_redo/replacer/api/replacer.lua:119> `

crash after trying to replace `default:cobble` with `ethereal:bush`

**Comment by do0dleme** [comment]
it happened again while trying to replace `ethereal:bush` with `moreblocks:super_glow_glass`

**Comment by fluxionary** [comment]
> multicraft

i'm having trouble replicating this locally. i'm half asleep, but it'd help if you can answer some general questions. 

can you point me at the exact version of multicraft you are using, which game you are using? (also, showing me the exact mods and commits would be helpful.

**Comment by do0dleme** [comment]
our server is on MultiCraft 2.0.1, minetest game. might this be an issue of another mod conflicting with it?

**Comment by fluxionary** [comment]
i'm gonna get to the bottom of this, but i'm on vacation for a few more days.

**Comment by fluxionary** [comment]
sorry this took a while. 

turns out the issue was with replacer_redo, not with fmod. the issue was that it was using the wrong API call to report when things couldn't be replaced for some reason. 

the fix should now be available in replacer redo, though it might take a day or something for the content DB to update.
